# Generated by Django 4.2.1 on 2023-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='rishi-image.jpg', upload_to='poem_images/'),
        ),
    ]
