# Generated by Django 4.2.2 on 2023-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
