# Generated by Django 4.2.2 on 2023-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
