# Generated by Django 4.2.2 on 2023-06-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_alter_poem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='slug',
        ),
    ]
