# Generated by Django 4.2.2 on 2023-06-22 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0015_poem_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
