# Generated by Django 4.2.2 on 2023-06-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0016_poem_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='image',
            new_name='authors_image',
        ),
        migrations.AddField(
            model_name='poem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='poem_images/'),
        ),
        migrations.AddField(
            model_name='poem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='poem_thumbnails/'),
        ),
    ]
