# Generated by Django 4.2.1 on 2023-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('love', 'Love'), ('motivational', 'Motivational'), ('sad', 'Sad')], default='uncategorized', max_length=100)),
            ],
        ),
    ]
