# Generated by Django 4.2.2 on 2023-06-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poem_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
