# Generated by Django 4.2.2 on 2023-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='page_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
