# Generated by Django 4.2.2 on 2023-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_remove_poem_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
    ]
