# Generated by Django 4.2.2 on 2023-06-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poems.poem')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
